spring.application.name=user-management
spring.profiles.active=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=7f3a9c1e2b4d6f8a9c0e1d2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
